// Counter
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER'
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER'
export const TOGGLE_SHOWING = 'TOGGLE_SHOWING'
export const SCROLL_POS = 'SCROLL_POS'
export const CURRENT_SECTION = 'CURRENT_SECTION'
export const SET_SECTION_REFS = 'SET_SECTION_REFS'
