// Counter
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER'
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER'
export const TOGGLE_SHOWING = 'TOGGLE_SHOWING'
export const SCROLL_POS = 'SCROLL_POS'
export const CURRENT_SECTION = 'CURRENT_SECTION'
export const CURRENT_SECTION_TOP = 'CURRENT_SECTION_TOP'
export const CURRENT_SECTION_Y = 'CURRENT_SECTION_Y'
export const SECTION_NAV_CLICK = 'SECTION_NAV_CLICK'
