export default {
    colors: {
      'rangoon': '#202312',
      'pine': "#34675c",
      'granite': "#b7b8b6",
      'blueSky': "#4cb5f5",
      'fields': "#b3c100",
      'copper': "#ddb071",
      'myWhite': 'whitesmoke',
      'headerBG' : '#070A0E',
      'sectionBG': 'whitesmoke',
      'sectionHeaderBG': '#783543',
      'myMaroon': '#783543',
    },
    fonts: {
      'comic': "font-family: 'Permanent Marker', cursive",
      'block': "font-family: 'Bungee', cursive",
      'handwriting': "font-family: 'Amatic SC', cursive",
      'bree': "font-family: 'Bree Serif', serif",
      'mainSerif': "font-family: 'Alegreya', serif",
      'mainSans': "font-family: 'Nunito', sans-serif",
    },
    'headerHeight': '40',
    'leftSitePadding': '96',
    'gridGutterWidth': 10,
    //'sectionHeaderX': (window.scrollY) => window.scrollY / 8,
}