import type { Metadata } from "next";
import { Inter, Russo_One, Silkscreen } from "next/font/google";
import React from "react";
import ThingsIDo from "./components/ThingsIDo";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const russoOne = Russo_One({
  subsets: ["latin"],
  variable: "--font-russo-one",
  display: "swap",
  weight: ["400"],
});

const silkscreen = Silkscreen({
  subsets: ["latin"],
  variable: "--font-silkscreen",
  display: "swap",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navLinks = [
  {
    href: "/about",
    text: "About",
  },
  {
    href: "/ensly-mogul",
    text: "Ensly Mogul",
  },
  {
    href: "/whatsoever",
    text: "Whatsoever",
  },
  {
    href: "/code",
    text: "Writing Code",
  },
  {
    href: "/music",
    text: "A Discography",
  },
  {
    href: "/maps",
    text: "Map drawing",
  },
  {
    href: "/universal-dork",
    text: "Universal Dork",
  },
  {
    href: "/polychrome",
    text: "Polychrome",
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <main
          className={`${inter.variable} ${russoOne.variable} ${silkscreen.variable} font-silkscreen flex flex-col h-screen gap-4 bg-gradient-to-br from-zinc-800 to-zinc-500`}
        >
          <nav className="border-b border-b-white w-full">
            <ThingsIDo />
          </nav>
          <div className="flex px-8 gap-12">
            <section className="flex flex-col gap-4">
              <h1 className="text-2xl">find out more ⤵</h1>
              <ul className="pl-56">
                {navLinks.map((link) => (
                  <li
                    key={link.href}
                    className="hover:text-green-500 transition-all hover:translate-x-4"
                  >
                    <a href={link.href}>{link.text}</a>
                  </li>
                ))}
              </ul>
            </section>
            <div className="flex-1">{children}</div>
          </div>
        </main>
      </body>
    </html>
  );
}
