import { Sidebar } from "@/components/Sidebar";
import type { Metadata } from "next";
import { Inter, Russo_One, Silkscreen } from "next/font/google";
import React from "react";
import { Header } from "../components/Header";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const russoOne = Russo_One({
  subsets: ["latin"],
  variable: "--font-russo-one",
  display: "swap",
  weight: ["400"],
});

const silkscreen = Silkscreen({
  subsets: ["latin"],
  variable: "--font-silkscreen",
  display: "swap",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <main
          className={`${inter.variable} ${russoOne.variable} ${silkscreen.variable} font-silkscreen flex flex-col h-screen gap-4 bg-zinc-950`}
        >
          <Header />
          <div className="flex gap-12">
            <Sidebar />
            <section className="flex-1 bg-zinc-900 hover:bg-zinc-800 rounded-l-3xl p-8  duration-400 transition-all">
              {children}
            </section>
          </div>
        </main>
      </body>
    </html>
  );
}
